---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required  packages in Redhat derivatives
  yum: name={{ item }} state=installed
  with_items: pound_pkgs
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ item }} state=installed update_cache=yes
  with_items: pound_pkgs
  environment: env
  when: ansible_os_family == 'Debian'

- name: Copy the pound.cfg template file
  template: src=pound.cfg.j2 dest={{ pound_cfg_file }}
  notify: 
   - restart pound

- name: Configure pound to start in /etc/default/pound
  lineinfile: dest=/etc/default/pound regexp=^startup= line=startup=1
  notify: 
   - restart pound
  when: ansible_os_family == 'Debian'

 
